version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: helper-db
    environment:
      POSTGRES_USER: doumi
      POSTGRES_PASSWORD: randompassword
      POSTGRES_DB: doumi
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
